-   id: format_check
    name: Commit Format Checker
    description: Validates commit format
    entry: commit_format_check.sh
    language: script
-   id: doctester
	name: Doctest
	description: Tester of doctest
	entry: doctester.sh
	language: script
